<a href="https://colab.research.google.com/github/HinataTsuji/data-science-toolkit/blob/main/Tutorial04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
dataframe=pd.read_csv('/content/drive/MyDrive/dataset.zip')     #pandas reading csv

In [ ]:
dataframe.head()

,Brand,Country,Year,Monthly_Production_Tonnes,Avg_Item_Price_USD,Release_Cycles_Per_Year,Carbon_Emissions_tCO2e,Water_Usage_Million_Litres,Landfill_Waste_Tonnes,Avg_Worker_Wage_USD,...,Instagram_Mentions_Thousands,TikTok_Mentions_Thousands,Sentiment_Score,Social_Sentiment_Label,GDP_Contribution_Million_USD,Env_Cost_Index,Sustainability_Score,Transparency_Index,Compliance_Score,Ethical_Rating
0,Shein,Indonesia,2017,574.51,19.31,16,11421.58,282.11,616.63,143.79,...,4655,3435,0.05,Neutral,608.51,0.49,29.12,61.19,13.95,1.46
1,Forever 21,Vietnam,2024,394.50,9.30,20,5571.01,289.22,795.11,167.78,...,9655,6285,-0.12,Positive,689.49,0.21,49.52,3.44,90.93,1.29
2,Uniqlo,India,2024,310.23,25.46,11,10969.00,116.39,364.33,97.81,...,8016,387,0.08,Neutral,439.78,0.63,96.53,60.70,27.60,1.48
3,Forever 21,USA,2017,218.65,13.17,13,13093.00,255.88,632.16,134.54,...,8254,1620,-0.06,Neutral,746.70,0.21,71.32,76.08,56.13,3.85
4,Zara,Indonesia,2016,1005.84,15.40,20,9548.40,142.07,830.10,144.33,...,1778,3292,-0.59,Neutral,571.42,0.95,59.89,69.48,88.05,3.12

In [ ]:
dataframe.tail()

,Brand,Country,Year,Monthly_Production_Tonnes,Avg_Item_Price_USD,Release_Cycles_Per_Year,Carbon_Emissions_tCO2e,Water_Usage_Million_Litres,Landfill_Waste_Tonnes,Avg_Worker_Wage_USD,...,Instagram_Mentions_Thousands,TikTok_Mentions_Thousands,Sentiment_Score,Social_Sentiment_Label,GDP_Contribution_Million_USD,Env_Cost_Index,Sustainability_Score,Transparency_Index,Compliance_Score,Ethical_Rating
2995,Zara,India,2020,549.36,17.77,21,11214.01,87.08,768.13,165.22,...,3079,3053,0.06,Negative,582.87,0.99,26.52,21.80,33.48,2.63
2996,Shein,USA,2021,670.54,18.05,24,10548.69,275.01,950.90,143.33,...,5297,2617,0.40,Positive,274.78,0.25,89.54,24.81,94.90,0.08
2997,Zara,China,2023,370.31,22.25,22,3385.09,211.81,906.82,104.30,...,6427,4743,-0.71,Negative,607.47,0.75,42.57,75.29,55.28,0.20
2998,Shein,Brazil,2015,649.20,23.00,14,10822.80,232.33,818.08,140.45,...,4487,5178,-0.34,Negative,509.98,0.32,5.59,16.66,20.73,2.89
2999,Zara,India,2018,602.77,13.95,28,8013.18,288.37,360.61,121.67,...,2927,7713,-0.53,Neutral,263.38,0.67,72.84,94.53,40.91,3.53

In [ ]:
dataframe.columns

Index(['Brand', 'Country', 'Year', 'Monthly_Production_Tonnes',
       'Avg_Item_Price_USD', 'Release_Cycles_Per_Year',
       'Carbon_Emissions_tCO2e', 'Water_Usage_Million_Litres',
       'Landfill_Waste_Tonnes', 'Avg_Worker_Wage_USD',
       'Working_Hours_Per_Week', 'Child_Labor_Incidents',
       'Return_Rate_Percent', 'Avg_Spend_Per_Customer_USD',
       'Shopping_Frequency_Per_Year', 'Instagram_Mentions_Thousands',
       'TikTok_Mentions_Thousands', 'Sentiment_Score',
       'Social_Sentiment_Label', 'GDP_Contribution_Million_USD',
       'Env_Cost_Index', 'Sustainability_Score', 'Transparency_Index',
       'Compliance_Score', 'Ethical_Rating'],
      dtype='object')

In [ ]:
dataframe.to_numpy()

array([['Shein', 'Indonesia', 2017, ..., 61.19, 13.95, 1.46],
       ['Forever 21', 'Vietnam', 2024, ..., 3.44, 90.93, 1.29],
       ['Uniqlo', 'India', 2024, ..., 60.7, 27.6, 1.48],
       ...,
       ['Zara', 'China', 2023, ..., 75.29, 55.28, 0.2],
       ['Shein', 'Brazil', 2015, ..., 16.66, 20.73, 2.89],
       ['Zara', 'India', 2018, ..., 94.53, 40.91, 3.53]], dtype=object)

My question is: In the last 5 years, how much percentage of SHEIN products' has over 50% of Environmental Cost Index and negative social sentinent?

*can state about relationship - environmental impact and how people are willing to change?*

production line and waste contribute to negative social and environmental impact? (e.g. child labor, workforce exploitation, carbon emission, water usage, landfill waste over 1k tonnes)

*please put each characteristic inside the question to make it specific*

What can we conclude from this fast fashion trend for the next 5 years? What can we do to decrease the percentage of SHEIN products' production impact by 5%?

2. This dataset has enough samples with 25 columns and 3000 rows. 5 brands (SHEIN, H&M, Forever 21, Zara, Uniqlo), Large consumer market countries (Bangladesh, Brazil, China, Germany, India, Indonesia, Turkey, UK, USA, Vietnam). Wide timeline from year 2015 to 2024, and lots of characteristics for the columns to observe and analyze from.

3. There are 25 columns that represent 25 features. It is enough.

4. We have approximately 50 samples/observation for each brand and country, thus it is enough.

5. The dataset consists of quantitative(numerical, discrete for Child_Labor, continuous for most of it) and qualitative(categorical) datatypes. Most of them are quantitative, while the qualitative (ordinal) data examples are "social sentinent". It can be represented using Tabular, Graphical, or Time Series visualization.

6. None of the columns have null values.

7. Featured Columns: Monthly_Production_Tonnes, Release_Cycles_Per_Year, Carbon_Emmissions, Water_Usage, Landfill_Waste, Working_Hours, Child_Labor_Incidents, Return_Rate, Social_Sentinent (whether we want to sway the public on reducing fast fashion purchases), Env_Cost, Sustainability_Score
Target output is the Carbon_Emmissions, Water_Usage, Landfill_Waste, Social_Sentinent, Env_Cost, Sustainability_Score, Ethical_Rating

8. No.

9. Going back to my question above. The type of question that can be asked is a relationship question. Or a comparison question between brands. Or a composition of environmental impact of fast fashion. Yes the dataset suits the question we are asking.

Further opinions: The data can be tidied into SHEIN -> countries_year for easier observation

In [ ]:
print(dataframe.isnull().sum())  # or use .any()

Brand                           0
Country                         0
Year                            0
Monthly_Production_Tonnes       0
Avg_Item_Price_USD              0
Release_Cycles_Per_Year         0
Carbon_Emissions_tCO2e          0
Water_Usage_Million_Litres      0
Landfill_Waste_Tonnes           0
Avg_Worker_Wage_USD             0
Working_Hours_Per_Week          0
Child_Labor_Incidents           0
Return_Rate_Percent             0
Avg_Spend_Per_Customer_USD      0
Shopping_Frequency_Per_Year     0
Instagram_Mentions_Thousands    0
TikTok_Mentions_Thousands       0
Sentiment_Score                 0
Social_Sentiment_Label          0
GDP_Contribution_Million_USD    0
Env_Cost_Index                  0
Sustainability_Score            0
Transparency_Index              0
Compliance_Score                0
Ethical_Rating                  0
dtype: int64